### PR TITLE
Initial stab at a Reading Club information page

### PR DESCRIPTION
**Pull request by IanConnolly**
Let's give this a shot shall we?

All feedback welcome.

### CODE REVIEW

**Comment by eoinhurrell** [comment]
This seems like a great idea, and if the the reading list so far is indicative I look forward to the discussion.

**Comment by IanConnolly** [comment]
@colmdoyle r?

**Comment by colmdoyle** [comment]
@IanConnolly You should have commit rights?

**Comment by IanConnolly** [comment]
@colmdoyle Nah, I'm in the `Members` group - no access to repos.

**Pull request merged**
