### PR TITLE
Update codeofconduct.md

### PR DESCRIPTION
**Pull request by colmdoyle**
Accounts should be people, not entities.

### CODE REVIEW

**Comment by conormcd** [comment]
Would this be a little clearer if it was emphasised that there should be a 1:1 human:account ratio?

**Comment by colmdoyle** [comment]
I think the verbage could do with some polish for sure, I'm just trying to flag the general change in policy first.

**Comment by colmdoyle** [comment]
The impetus for this PR is here - https://irishtechcommunity.slack.com/archives/events/p1449498984000816

**Comment by oisin** [comment]
A person should have one account, and each account should be one person. If you are posting on behalf of a company, say your own startup, or a place at which you work, that's fine. But you are posting it from _your_ account, not from a _company_ account.

**Comment by colmdoyle** [comment]
You words better than I do @oisin

**Comment by paulmwatson** [comment]
+1

**Comment by colmdoyle** [comment]
Ok, so my plan is to leave this around for a few days since it's potentially a change not everyone will agree with.

**Comment by No9** [comment]
:+1:

**Comment by micflan** [comment]
+1

**Pull request closed without merging**
