### PR TITLE
Created a channel list page.

### PR DESCRIPTION
**Pull request by jymian**
Created a channel list page.
- initial list was manually created, using the https://api.slack.com/methods/channels.list/test method
- all archived channels were removed
- where appropriate, the channel purpose was displayed

Open question: should the number of channel members be displayed?

### CODE REVIEW

**Comment by colmdoyle** [comment]
Do you want to link to `/channels` from somewhere?

**Comment by colmdoyle** [comment]
A screenshot would be nice too if you have the time

**Comment by jymian** [comment]
Yup, to both.
I figured that a separate PR for the page, and then the link, would make backing out one or the other easier.

**Comment by colmdoyle** [comment]
Fair enough. I'd be happy to take both at once in the future.

**Comment by jymian** [comment]
Looks like setting it as a page shows it up in the header :smiley:

**Comment by colmdoyle** [comment]
I totally knew that.

**Pull request merged**
